config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  get 'pages/home'
  get 'sign-in-development/:id', to: 'pages#sign_in_development', as: :sign_in_development
  devise_for :users
  get '/set_locale', to: 'application#set_locale'

  resources :activities
end

app/models/activity.rb
class Activity < ApplicationRecord
  FIELDS = %i[name].freeze
  extend Mobility
  translates :name, :description

  has_many :disciplines, dependent: :destroy
  has_many :activity_associations, dependent: :destroy
  has_many :associated_activities, through: :activity_associations

  validates :name, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
  # t('successfully') instead I18n.t('successfully')
  include AbstractController::Translation
end

app/models/check_point.rb
class CheckPoint < ApplicationRecord
  belongs_to :result_sampling

  has_many :results, dependent: :destroy
end

app/models/club.rb
class Club < ApplicationRecord
  extend Mobility
  translates :name

  belongs_to :venue, optional: true

  has_many :happenings, dependent: :destroy
  has_many :members, dependent: :destroy
  has_many :club_users, dependent: :destroy
  # has_many :users, through: :club_users # do not use this since club
  # users can be disabled, so better is to use active_users
  has_many :active_users, -> { where club_users: { status: :active } }, through: :club_users, source: :user
end

app/models/club_user.rb
class ClubUser < ApplicationRecord
  belongs_to :club
  belongs_to :user

  enum status: %i[unconfirmed active disabled]
end

app/models/crew.rb
class Crew < ApplicationRecord
  belongs_to :discipline_happening
  belongs_to :club, optional: true

  has_many :crew_races, dependent: :destroy
  has_many :member_crews, dependent: :destroy

  validate :_number_of_crew_match_discipline

  def _number_of_crew_match_discipline
    return unless discipline_happening

    target_number = discipline_happening.discipline.number_of_crew
    real_count = member_crews.length
    return if real_count == target_number

    errors.add(:base, t('crew_number_should_be_taget_count_instead_of_real_count',
                        target_count: target_number, real_count: real_count))
  end
end

app/models/crew_race.rb
class CrewRace < ApplicationRecord
  belongs_to :crew
  belongs_to :race

  has_many :results, dependent: :destroy
end

app/models/discipline.rb
class Discipline < ApplicationRecord
  extend Mobility
  translates :name

  belongs_to :activity

  has_many :discipline_happenings, dependent: :destroy
  has_many :races, dependent: :destroy
  has_many :check_points, dependent: :destroy

  enum gender: %i[man women mix]
end

app/models/happening.rb
class Happening < ApplicationRecord
  belongs_to :venue
  belongs_to :club, optional: true

  has_many :discipline_happenings, dependent: :destroy

  enum repeating: %i[no_repeating daily_repeating weekly_repeating yearly_repeating]

  validate :_end_date_greater_or_equal_start_date

  def _end_date_greater_or_equal_start_date
    return if end_date.blank? || start_date.blank?
    return if end_date >= start_date

    errors.add :end_date, t('can_not_be_greater_than_item_name', item_name: Happening.human_attribute_name(:start_date))
  end
end

app/models/member.rb
class Member < ApplicationRecord
  belongs_to :club
  belongs_to :person

  has_many :member_crews, dependent: :destroy
end

app/models/member_crew.rb
class MemberCrew < ApplicationRecord
  belongs_to :member
  belongs_to :crew
end

app/models/person.rb
class Person < ApplicationRecord
  extend Mobility
  translates :name

  has_many :members, dependent: :destroy
end

app/models/race.rb
class Race < ApplicationRecord
  belongs_to :discipline_happening

  has_many :crews, dependent: :destroy

  enum category: %i[final semifinal qualification]
end

app/models/result.rb
class Result < ApplicationRecord
  belongs_to :crew_race
  # if check_points if blank that is final result, otherwise it is one of the
  # crew_race.race.discipline_happening.result_sampling.check_points
  belongs_to :check_point, optional: true
end

app/models/result_sampling.rb
class ResultSampling < ApplicationRecord
  extend Mobility
  translates :name

  belongs_to :happening

  has_many :discipline_happening, dependent: :destroy
  has_many :check_points, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  has_many :club_users, dependent: :destroy

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/venue.rb
class Venue < ApplicationRecord
  extend Mobility
  translates :name

  has_many :happenings, dependent: :destroy
  has_many :clubs, dependent: :nullify
end

app/helpers/application_helper.rb
module ApplicationHelper
  def android_app?
    request.env['HTTP_USER_AGENT'] == 'move-results-app'
  end
end

app/helpers/pages_helper.rb
module PagesHelper
  def login_layout(login_title = nil)
    @login_title = login_title
    @login_layout = true
  end

  def login_layout?
    @login_layout
  end

  def login_title
    @login_title
  end

  def title(name)
    @title = name
  end

  def fetch_title
    @title || fetch_breadcrumb_list.keys.last
  end

  def breadcrumb(list)
    @breadcrumb = list
  end

  def fetch_breadcrumb_list
    @breadcrumb || {}
  end
end

app/helpers/translate_helper.rb
module TranslateHelper
  # t_crud 'edit', User
  # t_crud 'are_you_sure_to_remove_item_name', User
  def t_crud(action, model_class)
    # we are using accusative here
    if action.include? 'item_name'
      t(action, item_name: t('activerecord.models.' + model_class.name.underscore + '.accusative'))
    else
      "#{t(action)} #{t('activerecord.models.' + model_class.name.underscore + '.accusative')}"
    end
  end

  # t_notice 'successfully_created', User
  def t_notice(notice, model_class)
    t("data_item_name_#{notice}", item_name: model_class.model_name.human.titleize)
  end

  def t_are_you_sure
    if android_app?
      nil
    else
      t('are_you_sure')
    end
  end
end

app/views/layouts/_breadcrumb.html.erb
<nav aria-label="breadcrumb" class='d-flex'>
  <ol class="flex-grow-1 breadcrumb breadcrumb--no-margin-bottom">
    <li>
      <%= link_to root_path do %>
        <%= image_tag 'logo.svg', class: 'breadcrumb__image--max-width' %>
      <% end %>
    </li>
    <li class='breadcrumb-item d-none d-sm-block'>
      <%= link_to root_path do %>
        <%= t('home') %>
      <% end %>
    </li>
    <% fetch_breadcrumb_list.each_with_index do |(text, link), i| %>
      <% last_item = i == fetch_breadcrumb_list.length - 1 %>
      <li class="breadcrumb-item <%= 'active' if last_item %>" <%= 'aria-current="page"' if last_item %>>
        <% if link.present? %>
          <%= link_to link do %>
            <%= text %>
          <% end %>
        <% else %>
          <span id='breadcrumb-last'>
            <%= text %>
          </span>
        <% end %>
      </li>
    <% end %>
  </ol>
  <div class='align-self-center'>
    <%= button_tag class: "btn btn-link", 'data-controller': 'activate', 'data-action': 'activate#toggle', 'data-activate-selector': '#sidebar,.sidebar__overlay' do %>
      <i class="icon-menu-outline d-sm-none" aria-hidden="true"></i>
      <span class='d-none d-sm-block'><%= current_user.name %></span>
    <% end %>
  </div>
</nav>

app/views/layouts/_choose_language.html.erb
<% request_path = request.path
   request_path = '' if request.post?
 %>
<% cache 'language' do %>
  <div class="flags-dropdown nav-item dropdown">
    <a role="button" class="nav-link dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
      <% if I18n.locale == :en %>
        <%= image_tag 'flag-usa.png' %>
      <% else %>
        <%= image_tag 'flag-serbia.png' %>
      <% end %>
    </a>
    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
      <li class="dropdown-item"><a href="<%= root_url subdomain: nil, domain: Constant::DOMAINS[Rails.env.to_sym][:sr] %>"><%= image_tag 'flag-serbia.png' %> <%= t('current_language', locale: :sr) %></a></li>
      <li class="dropdown-item"><a href="<%= root_url subdomain: nil, domain: Constant::DOMAINS[Rails.env.to_sym][:'sr-latin'] %>"><%= image_tag 'flag-serbia.png' %> <%= t('current_language', locale: :'sr-latin') %></a></li>
      <li class="dropdown-item"><a href="<%= root_url subdomain: nil, domain: Constant::DOMAINS[Rails.env.to_sym][:en] %>"><%= image_tag 'flag-usa.png' %> <%= t('current_language', locale: :en) %></a></li>
    </ul>
  </div>
<% end %>

app/views/layouts/_flash_notice_alert.html.erb
<div data-controller='flash' data-flash-message='<%= j notice %>'>
  <div data-test='notice-holder' class='d-none-opacity'><%= notice %></div>
  <% if notice.present? %>
    <button class='flash-notice-alert-repeat' data-action='flash#show' title='<%= t('last_message') %>'><i class="demo-icon icon-cw"></i>
</button>
  <% end %>
</div>
<div data-controller='flash' data-flash-message='<%= j alert %>' data-flash-alert='true'>
  <div data-test='alert-holder' class='d-none-opacity'><%= alert %></div>
  <% if alert.present? %>
    <button class='flash-notice-alert-repeat' data-action='flash#show' title='<%= t('last_message') %>'><i class="demo-icon icon-cw"></i>
  <% end %>
</div>

app/views/layouts/_login_layout.html.erb
<body>
  <% if current_user %>
    <div class='text-right pr-2'>
      <strong><%= current_user.email %></strong>
      <%= link_to t('sign_out'), destroy_user_session_path, method: :delete %>
    </div>
  <% end %>
  <div class='text-center text-muted'>
    <%= link_to root_path do %>
      <%= image_tag 'logo.svg', class: 'login-logo--max-width mx-auto p-2' %>
    <% end %>
    <h2 class='h6'><%= login_title %></h2>
  </div>
  <div class='container'>
    <div class='login-wrapper--max-width mx-auto'>
      <div class="<%= 'login--max-width mx-auto bg-white shadow p-4' unless controller_name == 'companies' %>">
        <%= yield %>
      </div>
    </div>
  </div>
  <%= render 'layouts/flash_notice_alert' %>
</body>

app/views/layouts/_navigation.html.erb
<%# on responsive there are two different horizontal navigations, one for admin and one for non admin
  breakpoint is sm
%>
<%
  left_navigation ||= false
%>
<div class='bg-light <%= left_navigation ? 'd-none d-sm-inline-block text-left left-navigation--min-width' : 'sticky-footer d-sm-none' %>'>
  <ul class='nav nav-pills <%= left_navigation ? 'flex-column ' : 'justify-content-around flex-nowrap ' %>'>
    <%# <li class='nav-item flex-fill'> %>
    <%#   <%= link_to activities_path, class: "nav-link nav-link--no-padding rounded-0 #{'active' if controller_name == 'activities'}" do %1> %>
    <%#     <div class='d-flex flex-column-reverse d-sm-inline-flex flex-sm-row align-items-center'> %>
    <%#       <i class='fas fa-search fa-fw mx-1' aria-hidden='true'></i> %>

    <%#       <span><%= Activity.model_name.human count: 2 %1></span> %>
    <%#     </div> %>
    <%#   <% end %1> %>
    <%# </li> %>
    <% if current_user.superadmin? %>
      <li class='nav-item d-none d-sm-block'>
        <span class='text-success'>
          <%= t('admin_pages') %>
        </span>
      </li>
      <li class='nav-item d-none d-sm-block'>
        <%= link_to activities_path, class: "nav-link nav-link--no-padding rounded-0 #{'active' if controller_name == 'activities'}" do %>
          <div class='d-flex flex-column-reverse d-sm-inline-flex flex-sm-row align-items-center'>
            <i class='fas fa-grip-horizontal fa-fw mx-1' aria-hidden='true'></i>
            <span><%= Activity.model_name.human(count: 2) %></span>
          </div>
        <% end %>
      </li>
    <% end %>
  </ul>
</div>

app/views/layouts/_sidebar.html.erb
<nav id='sidebar' class=''>
  <div class='d-flex align-items-center'>
    <div class='text-secondary'><%= truncate current_user.email, length: 34 %></div>
    <div class='ml-auto'>
      <%= button_tag class: 'btn btn-link text-primary', 'data-controller': 'activate', 'data-action': 'activate#toggle', 'data-activate-selector': '#sidebar,.sidebar__overlay' do %>
        <i class="icon-cancel-outline"></i>
      <% end %>
    </div>
  </div>
  <div class='list-group list-group-flush'>
    <%= link_to "<i class='icon-mobile fa-fw mx-1'></i>#{t('home')}".html_safe, root_path, class: "list-group-item list-group-item-action text-primary #{'active' if controller_name == 'pages' }" %>
    <div class='d-sm-none'>
      <% if current_user.superadmin? %>
        <span class='text-success'>
          <%= t('admin_pages') %>
        </span>
        <%= link_to "<i class='fas fa-grip-horizontal fa-fw mx-1'></i>#{Activity.model_name.human(count: 2)}".html_safe, activities_path, class: "list-group-item list-group-item-action text-primary #{'active' if controller_name == 'activities'}" %>
      <% end %>
    </div>
    <%= link_to "<i class='icon-logout mx-1'></i>#{t('my_devise.sign_out')}".html_safe, destroy_user_session_path, method: :delete, class: 'list-group-item list-group-item-action text-primary' %>
  </div>
</nav>
<div class='sidebar__overlay' data-controller='activate' data-action='click->activate#toggle' data-activate-selector='#sidebar,.sidebar__overlay'></div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= fetch_title.present? ? fetch_title + ' | ' : '' %><%= t('site_title') %></title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <% if login_layout? %>
    <%= render 'layouts/login_layout' %>
  <% else %>
    <body>
      <% if current_user.present? %>
        <%= render 'layouts/sidebar' %>
        <%= render 'layouts/breadcrumb' %>

        <div class='d-flex align-items-stretch'>
          <%= render 'layouts/navigation', left_navigation: true %>
          <div class='p-2 flex-grow-1'>
            <%= yield %>
          </div>
        </div>

        <%= render 'layouts/navigation' %>
      <% elsif controller_name == 'pages' && action_name == 'home' %>
        <%= yield %>
      <% else %>
        <%= render 'layouts/navbar_not_logged_in' %>
        <%= yield %>
      <% end %>
      <%= render 'layouts/flash_notice_alert' %>
    </body>
  <% end %>
</html>

app/views/pages/home.html.erb
<ul class='nav'>
  <li class='nav-item px-1 dropdown'>
    <a class='nav-link dropdown-toggle' href='#' id='navbarDropdown' role='button' data-toggle='dropdown' aria-haspopup='true' aria-expanded='false'>
      <%= image_tag "flagpedia.net/#{locale}.png", class: 'flag--max-width', 'data-test': 'language-holder' %>
    </a>
    <div class="dropdown-menu dropdown-menu--without-min-width" aria-labelledby="navbarDropdown">
      <% I18n.available_locales.each do |locale| %>
        <%= link_to set_locale_path(locale: locale), 'data-turbolinks': false, class: 'dropdown-item' do %>
          <%= image_tag "flagpedia.net/#{locale}.png", class: 'flag--max-width' %>
          <%= t("language_name.#{locale}") %>
        <% end %>
      <% end %>
    </div>
  </li>
  <li class='nav-item px-1'>
    <% if current_user %>
      <strong><%= current_user.email %></strong>
      <%= link_to t('my_devise.sign_out'), destroy_user_session_path, method: :delete %>
    <% else %>
      <%= link_to t('my_devise.sign_in'), new_user_session_path %>
    <% end %>
  </li>
</ul>

<div data-controller="hello">
 <h1 data-target="hello.output"></h1>
</div>